version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:6333/collections || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  mock_llm:
    build:
      context: ./services/mock_llm
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_PORT=8000
    ports:
      - "8888:8000"
    depends_on:
      - redis

  llm_generator_1:
    build:
      context: ./services/llm_generator
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_PORT=8000
      - LLM_SERVICE_URL=http://mock_llm:8000
    ports:
      - "11434:8000"
    depends_on:
      - redis
      - mock_llm
    restart: unless-stopped

  llm_generator_2:
    build:
      context: ./services/llm_generator
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_PORT=8000
      - LLM_SERVICE_URL=http://mock_llm:8000
    ports:
      - "11435:8000"
    depends_on:
      - redis
      - mock_llm
    restart: unless-stopped

  api_gateway:
    build:
      context: ./services/api_gateway
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  encoder_service:
    build:
      context: ./services/encoder_service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - EMBEDDING_DEVICE=cpu
      - API_PORT=8000
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - qdrant
    restart: unless-stopped

  retriever_service:
    build:
      context: ./services/retriever_service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - API_PORT=8000
    depends_on:
      - redis
      - qdrant
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./rag-optimizer/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - api_gateway

volumes:
  qdrant_storage:
